# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  pool: 5

development:
  <<: *default
  database: <%= ENV['DATABASE'] || 'development' %>

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
